# Generated by Django 6.0.1 on 2026-04-08 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_logs", "0003_topic_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="topic",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
